### ISSUE TITLE
Innecesario ConstraintLayout

### ISSUE THREAD

**Issue by manelcc** [adrianfanjul/ComprasFamiliares#1]
Puedes poner el **app:layout_behavior="@string/appbar_scrolling_view_behavior"** dentro de **FragmentContainerView** y asi te evitas tener que poner el ConstraintLayout

https://github.com/adrianfanjul/ComprasFamiliares/blob/562ff4471c3ebe24678221234b8436a16022c9bd/app/src/main/res/layout/activity_login.xml#L23-L40

**Comment by adrianfanjul** [comment]
solucionado
