### ISSUE TITLE
Innecesario ConstraintLayout en ACTIVITY LOGIN-GROUP-LISTACOMPRA

### ISSUE THREAD

**Issue by manelcc** [adrianfanjul/ComprasFamiliares#2]
Puedes poner el **app:layout_behavior="@string/appbar_scrolling_view_behavior"** dentro de **FragmentContainerView** y asi te evitas tener que poner el ConstraintLayout

**LOGIN**
https://github.com/adrianfanjul/ComprasFamiliares/blob/562ff4471c3ebe24678221234b8436a16022c9bd/app/src/main/res/layout/activity_login.xml#L23-L40

**GROUPS**
https://github.com/adrianfanjul/ComprasFamiliares/blob/562ff4471c3ebe24678221234b8436a16022c9bd/app/src/main/res/layout/activity_group.xml#L25-L42

**LISTA COMPRA**
https://github.com/adrianfanjul/ComprasFamiliares/blob/562ff4471c3ebe24678221234b8436a16022c9bd/app/src/main/res/layout/activity_lista_compra.xml#L23-L40

**Comment by adrianfanjul** [comment]
solucionado
