### ISSUE TITLE
Porque Utilizas la propiedad textcolor?

### ISSUE THREAD

**Issue by manelcc** [adrianfanjul/ComprasFamiliares#3]
Si te fijas el appearance es el inverse y ese appearance tiene el color de texto secondary, por lo tanto no hace falta indicar el color. Supongo que al no funcionar el appearance has puesto el color.
Pero fijate que te falta la definición de los estilos de los Inputs layouts => https://material.io/components/text-fields/android#theming-text-fields
Es en los estilos de los InputsLayouts donde deberas de poner los appearance no en el layout. El layout con su estilo ya te pintara el color que quieres.

https://github.com/adrianfanjul/ComprasFamiliares/blob/562ff4471c3ebe24678221234b8436a16022c9bd/app/src/main/res/layout/fragment_create_group.xml#L58

https://github.com/adrianfanjul/ComprasFamiliares/blob/562ff4471c3ebe24678221234b8436a16022c9bd/app/src/main/res/layout/fragment_create_group.xml#L50-L58

**Comment by adrianfanjul** [comment]
solucionado
