### ISSUE TITLE
NAVEGACION HACIA ATRAS

### ISSUE THREAD

**Issue by manelcc** [adrianfanjul/ComprasFamiliares#6]
@adrianfanjul veo que para volver atras de una navegación estas creando una nueva dirección. Eso no debe ser así.
Las Activitys o Fragments se apilan y el back vuelve al anterior de la pila.
Por ejemplo en la siguiente funcion podrías poner un **navigateUp** => O como tienes la clase base un **navigateBack**

https://github.com/adrianfanjul/ComprasFamiliares/blob/9e47776adb69d93bf97c287d4b43c7aa016c4ace/app/src/main/java/es/adrianfg/comprasfamiliares/presentation/features/listaCompra/fragments/ListaCompraAddFragment.kt#L83-L86

Revisar en otras clases

**Comment by adrianfanjul** [comment]
Solucionado
